---
title: MIB data 
author: Jono Tuke
date: today
date-format: long
format: 
  html: 
    self-contained: true
    df-print: tibble
editor_options: 
  chunk_output_type: console
execute: 
  warning: false
  message: false
---

```{r}
#| label: setup
pacman::p_load(tidyverse, targets, gt)
here::here()
```

# Data

```{r}
ibd_file <- "dev/06-mib-data/2026-03-30-ibd.tsv"
```


```{r}
meta_file <- "dev/06-mib-data/2026-03-30-meta.tsv"
```


```{r}
#| eval: false
g <- create_ibd_network(ibd_file, meta_file, filter_on_meta = TRUE)
write_rds(g, "dev/06-mib-data/mib-graph.rds")
```


```{r}
g <- read_rds("dev/06-mib-data/mib-graph.rds")
g
```

# Node attributes
When you run node attributes, you get only name and site. 
```{r}
get_node_attributes(g, type = "cat")
```

Looking at the attributes
```{r}
igraph::vertex_attr_names(g)
```

we see that Ben has added extra columns with centrality measures. So to fix, we remove the centrality measures directly. 

# Ringbauer


```{r}
g |> get_ringbauer_measures("simple_culture")
```